name: Semantic release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js

        uses: actions/setup-node@v1

        with:
          node-version: 20

      - name: Install dependencies

        run: npm install

      - name: Build app

        run: npm run build

      - name: Semantic release

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
